"""Users table

Revision ID: dbd1a476142b
Revises: 
Create Date: 2018-10-27 18:22:33.300284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd1a476142b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('first_name', sa.String(length=250), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('deriv_date', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deriv_date'), 'users', ['deriv_date'], unique=False)
    op.create_index(op.f('ix_users_dob'), 'users', ['dob'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_dob'), table_name='users')
    op.drop_index(op.f('ix_users_deriv_date'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
