"""superusers field

Revision ID: dccc48639818
Revises: 2b6f51dc957b
Create Date: 2018-11-13 15:05:40.079782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dccc48639818'
down_revision = '2b6f51dc957b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('superuser', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'superuser')
    # ### end Alembic commands ###
